app/anyadir/views.py
from flask import (Blueprint, render_template, request, flash)
from app.db import Productos, db
from flask_login import login_required


anyadir = Blueprint(
            'anyadir',
            __name__,
            template_folder="app/templates",
            static_folder='static'
        )


@anyadir.route("/anadirProducto", methods=['GET', 'POST'])
@login_required
def add_prod():
    if request.method == 'POST':
        if not request.form['nombre'] or not request.form['categoria'] or not request.form['ubicacion'] or not request.form['cantidad'] or not request.form['precio']:
            flash('Introduzca todos los datos', 'error')
        else:
            nombre = request.form['nombre']
            categoria = request.form['categoria']
            ubicacion = request.form['ubicacion']
            cantidad = request.form['cantidad']
            precio = request.form['precio']
            producto = Productos(nombre=nombre, categoria=categoria, ubicacion=ubicacion, cantidad=cantidad, precio=precio)
        db.session.add(producto)
        db.session.commit()
        flash('producto correctamente añadido')
        return('dasds')
    return render_template("anyadirProducto.html")

app/eliminar/views.py
from flask import (Blueprint, render_template, request, flash, redirect)
from app.db import (Productos, Pedidos, Usuarios, db)
from sqlalchemy.exc import SQLAlchemyError
from flask_login import login_required

eliminar = Blueprint(
            'eliminar',
            __name__,
            template_folder="app/templates",
            static_folder='static'
        )
prodEliminado = ''


@eliminar.route("/eliminarPedido", methods=['GET', 'POST'])
@login_required
def rm_ped():
    if request.method == 'POST':
        if not request.form['id_pedido']:
            flash('Debe introducir un id de Pedido')
        else:
            idPedido = request.form['id_pedido']
            q = "DELETE FROM pedidos WHERE id=" + idPedido
            try:
                db.session.execute(q)
                db.session.commit()
            except SQLAlchemyError:
                flash('Error al eliminar Pedido')
            else:
                flash('Pedido eliminado')
        return redirect('/eliminarPedido')
    else:
        pedidos = Pedidos.query.all()
        usuarios = Usuarios.query.all()
        productos = Productos.query.all()
    return render_template("eliminarPedido.html", pedidos=pedidos, usuarios=usuarios, productos=productos)


@eliminar.route("/eliminarProducto", methods=['GET', 'POST'])
@login_required
def rm_prod():
    if request.method == 'POST':
        if not request.form['id_producto']:
            flash('Debe introducir un id de Producto')
        else:
            idProducto = request.form['id_producto']
            p = "DELETE FROM pedidos WHERE id_productos=" + idProducto
            q = "DELETE FROM productos WHERE id=" + idProducto
            try:
                db.session.execute(p)
                db.session.commit()
                db.session.execute(q)
                db.session.commit()
            except SQLAlchemyError:
                flash('Error al eliminar Producto')
            else:
                flash('Producto eliminado')
        return redirect('/eliminarProducto')
    else:
        productos = Productos.query.all()
    return render_template("eliminarProducto.html", productos=productos)

app/inicio/__init__.py
from app.inicio.views import *  # expose all views at the blueprint level

app/inicio/views.py
from flask import Blueprint, render_template


inicio = Blueprint(
            'inicio',
            __name__,
            template_folder="templates",
            static_folder='static'
        )


@inicio.route("/")
def inicio_view():
    textoInicial = "Pagina de inicio"
    return render_template("inicio//inicio.html", textoInicial=textoInicial)

app/logIn/__init__.py
from app.logIn.views import *

app/logIn/views.py
from flask import (Blueprint, render_template, request, redirect)
from flask_login import current_user, login_user, logout_user
from app.db import Usuarios, db


import sys
logIn = Blueprint(
            'logIn',
            __name__,
            template_folder="app/templates",
            static_folder='static'
        )


@logIn.route('/login', methods=['POST', 'GET'])
def login():
    if current_user.is_authenticated:
        return redirect('/inicio.html')
    if request.method == 'POST':
        email = request.form['email']
        user = Usuarios.query.filter_by(email=email).first()
        if user is not None and user.check_password(request.form['password']):
            login_user(user)
            return redirect('/')
    else:
        return render_template('logIn.html')
    return render_template('logIn.html')


@logIn.route('/register', methods=['POST', 'GET'])
def register():
    if current_user.is_authenticated:
        return redirect('/inicio')
    if request.method == 'POST':
        email = request.form['email']
        nombre = request.form['nombre']
        password = request.form['password']
        direccion = request.form['direccion']
        numero = request.form['telefono']
        if Usuarios.query.filter_by(email=email).first():
            usuarios = Usuarios.query.filter_by(email=email)
            usuarios_name = '<ul>'
            for usuario in usuarios:
                usuarios_name += '<li>' + usuario.nombre + ', ' + usuario.direccion + '</li>'
                usuarios_name += '</ul>'
            print(usuarios_name, file=sys.stdout)
            return ('Email already Present')
        user = Usuarios(email=email, nombre=nombre, numero=numero, direccion=direccion)
        user.set_password(password)
        db.session.add(user)
        db.session.commit()
        return redirect('/login')
    return render_template('registro.html')


@logIn.route('/logout')
def logout():
    logout_user()  # session.pop('user') help to remove the session from the browser
    return redirect('/')

app/main/__init__.py
from app.main.views import *

app/main/views.py
from flask import (Blueprint, render_template)

Main = Blueprint(
            'Main',
            __name__,
            template_folder="app/templates",
        )


@Main.route('/main')
def main():
    return render_template("main.html")

app/stats/__init__.py
from app.stats.views import *

app/stats/views.py
from flask import (Blueprint, render_template)
from app.db import Usuarios, Productos, Pedidos
from sqlalchemy import func
from flask_login import login_required, current_user
Stats = Blueprint(
            'Stats',
            __name__,
            template_folder="app/templates",
        )


@Stats.route("/usuarios", methods=["GET"])
@login_required
def usuarios():
    usuarios = Usuarios.query.with_entities(Usuarios.email, Usuarios.nombre, Usuarios.direccion, Usuarios.numero).all()
    cantidad = Usuarios.query.with_entities(Usuarios.direccion, func.count(Usuarios.direccion)).group_by(Usuarios.direccion).all()
    return render_template("usuarios.html",  usuarios=usuarios, cantidades=cantidad, pedidos=pedidos)


@Stats.route("/almacenes", methods=["GET"])
@login_required
def almacenes():
    productos = Productos.query.all()
    cantidad = Productos.query.with_entities(Productos.ubicacion, func.count(Productos.ubicacion)).group_by(Productos.ubicacion).all()
    return render_template("almacenes.html",  productos=productos, pedidos=pedidos, cantidades=cantidad)


@Stats.route("/pedidos", methods=["GET"])
@login_required
def pedidos():
    pedidos = Usuarios.query.all()
    print(pedidos.nombre)
    return render_template("pedidos.html",  pedidos=pedidos)


@Stats.route("/stats")
@login_required
def stats():
    print("bbbbb")
    print(current_user)
    print("aaaaa")
    usuarios = Usuarios.query.with_entities(Usuarios.id, Usuarios.nombre, Usuarios.direccion).all()
    pedidos = Pedidos.query.all()
    productos = Productos.query.all()
    cnt_estado = Pedidos.query.with_entities(Pedidos.estado, func.count(Pedidos.estado)).group_by(Pedidos.estado).all()
    print(cnt_estado)
    cnt_productos = Pedidos.query.with_entities(Pedidos.id_productos, func.count(Pedidos.id_productos)).group_by(Pedidos.id_productos).all()
    cnt_usuarios = Pedidos.query.with_entities(Pedidos.id_usuario, func.count(Pedidos.id_usuario)).group_by(Pedidos.id_usuario).all()
    print(pedidos)
    return render_template("stats.html", cnt_usuarios=cnt_usuarios, cnt_productos=cnt_productos, cnt_estado=cnt_estado, usuarios=usuarios, pedidos=pedidos, productos=productos)

app/tienda/__init__.py
from app.tienda.views import *

app/tienda/views.py
from flask import (Blueprint, render_template, request)
from app.db import Productos
from flask_login import current_user
Tienda = Blueprint(
            'Tienda',
            __name__,
            template_folder="app/templates",
        )


@Tienda.route('/<path:path>.html', methods=['POST', 'GET'])
def page(producto):
    producto = request.form['producto']
    return render_template('producto.html', producto=producto)


@Tienda.route('/')
def index():
    productos = Productos.query.order_by(Productos.nombre).all()
    if 'prod' in request.form:
        print('aaaaaaaaaaa')
        producto = request.form['producto']
        return render_template('producto.html', producto=producto)
    return render_template('tienda.html', current_user=current_user, productos=productos)

app/templates/almacenes.html
{% extends 'main.html' %}
{% block title %}<title>Stock</title>{% endblock %}
{% block scripts %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.5.0/Chart.min.js"></script>

{% endblock %}
{% block contenido %}
    <div class="contenedorDatos">
        <table class="table">
            <thead class="thead-dark">
                <tr>
                    <th class="columna" scope="col">Ubicación</th>
                    <th class="columna" scope="col">Nombre</th>
                    <th class="columna" scope="col">Cantidad</th>
                    <th class="columna" scope="col">Categoria</th>
                </tr>
            </thead>
            <tbody>
                {% for producto in productos %}
                    <tr>
                        <td>{{producto.ubicacion}}</td>
                        <td>{{producto.nombre}}</td>
                        <td>{{producto.cantidad}}</td>
                        <td>{{producto.categoria}}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>

        <nav>
            <div class="nav nav-tabs" id="nav-tab" role="tablist">
                <a class="nav-item nav-link active" id="nav-usuCiu-tab" data-toggle="tab" href="#nav-usuCiu" role="tab" aria-controls="nav-usuCiu" aria-selected="true">Productos por almacen</a>
            </div>
        </nav>
        <div class="tab-content" id="nav-tabContent">
            <div class="tab-pane fade show active" id="nav-usuCiu" role="tabpanel" aria-labelledby="nav-usuCiu-tab">
                <canvas id="chartProductosAlma" width="400" height="400"></canvas>
            </div>
        </div>
        <script>
            var ctx = document.getElementById("chartProductosAlma");
            var dynamicColors = function() {
                var r = Math.floor(Math.random() * 255);
                var g = Math.floor(Math.random() * 255);
                var b = Math.floor(Math.random() * 255);
                return "rgb(" + r + "," + g + "," + b + ")";
            };

            var chartProductosAlma = new Chart(ctx, {
                type: 'bar',
                data: {
                    labels: [{% for item in cantidades %}
                        "{{ item[0] }}",
                    {% endfor %}],
                    datasets: [{
                        label: 'Productos por almacen',
                        backgroundColor: [
                            {% for item in cantidades %}
                                dynamicColors().toString(),
                            {% endfor %} 
                        ],
                        data: [{% for item in cantidades %}
                            "{{ item[1] }}",
                        {% endfor %}],
                    }]
                }
            });
        </script>
    </div>
{% endblock %}

app/templates/anyadirProducto.html
{% extends 'main.html' %}
{% block title %}<title>Añadir producto</title>{% endblock %}

{% block contenido %}
<div class="contenedorDatos">
    <div class="contenedorAnyadir">
        <p class="invisible"> . </p>
        <h2 class="titulo">Añadir Un Nuevo Producto</h2>
        <form id="formAddProducto" method="post">
            <input type="text" class="form-control inputAdd" name="nombre" placeholder="Nombre" required="true" autofocus="" />
            <input type="text" class="form-control inputAdd" name="categoria" placeholder="Categoria" required="true" autofocus="" />
            <input type="text" class="form-control inputAdd" name="ubicacion" placeholder="Ubicacion" required="true" autofocus="" />
            <input type="text" class="form-control inputAdd" name="cantidad" placeholder="Cantidad" required="true" autofocus="" />
            <input type="text" class="form-control inputAdd" name="precio" placeholder="Precio" required="true" autofocus="" />
            <button class="btn btn-lg btn-primary btn-block botonAdd" type="submit">Nuevo Producto</button>
        </form>
    </div>
</div>
{% endblock %}

app/templates/eliminarPedido.html
{% extends 'main.html' %}
{% block title %}<title>Eliminar Pedido</title>{% endblock %}
{% block scripts %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.5.0/Chart.min.js"></script>

{% endblock %}
{% block contenido %}
<div class="contenedorDatos">
    <p class="invisible"> . </p>
    <h2 class="tituloElim">Eliminar Pedido</h2>
    <table class="table">
        <thead class="thead-dark">
            <tr>
                <th class="columna" scope="col">ID PEDIDO</th>
                <th class="columna" scope="col">PRODUCTO</th>
                <th class="columna" scope="col">USUARIO</th>
            </tr>
        </thead>
        <tbody>
            {% for pedido in pedidos %}
                <tr>
                    <td>{{pedido.id}}</td>
                    {% for producto in productos %}
                        {% if producto.id==pedido.id_productos %}
                            <td>{{producto.nombre}}</td>
                        {% endif %}
                    {% endfor %}
                    {% for usuario in usuarios %}
                        {% if usuario.id==pedido.id_usuario %}
                            <td>{{usuario.nombre}}</td>         
                        {% endif %}
                    {% endfor %}
                </tr>
            {% endfor %}
        </tbody>
    </table>
    <div class="contenedorEliminar">
        <form id="formPedido" method="post">
            <input type="text" class="form-control inputAdd" name="id_pedido" placeholder="Id Pedido" required="true" autofocus="" />
            <button class="btn btn-lg btn-primary btn-block botonAdd" type="submit">Eliminar Pedido</button>
        </form>
    </div>
</div>
{% endblock %}

app/templates/eliminarProducto.html
{% extends 'main.html' %}
{% block title %}<title>Eliminar Producto</title>{% endblock %}
{% block scripts %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.5.0/Chart.min.js"></script>

{% endblock %}
{% block contenido %}
<div class="contenedorDatos">
    <p class="invisible"> . </p>
    <h2 class="tituloElim">Eliminar Producto</h2>
    <table class="table">
        <thead class="thead-dark">
            <tr>
                <th class="columna" scope="col">ID PRODUCTO</th>
                <th class="columna" scope="col">NOMBRE</th>
            </tr>
        </thead>
        <tbody>
            {% for producto in productos %}
                <tr>
                    <td>{{producto.id}}</td>
                    <td>{{producto.nombre}}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    <div class="contenedorEliminar">
        <form id="form" method="post">
            <input type="text" class="form-control inputAdd" name="id_producto" placeholder="Id Producto" required="true" autofocus="" />
            <button class="btn btn-lg btn-primary btn-block botonAdd" type="submit">Eliminar Producto</button>
        </form>
    </div>
</div>
{% endblock %}

app/templates/inicio.html
{% block inicio %}



{% endblock %}

app/templates/logIn.html
{% extends 'main.html' %}
{% block title %}<title>Log In</title>{% endblock %}
{% block contenido %}
<div class="bodyLogin">
    <div class="loginContainer">
        <form class="form-signin" method="post">
            <h2>Iniciar Sesión</h2>
            <input type="text" class="form-control" name="email" placeholder="Email" required="true" autofocus="" />                        
            <input type="password" class="form-control" name="password" placeholder="Password" required="true"/>
            <label class="textoCheckbox"><input type="checkbox" value="Recordarme" id="recordarUsu" name="recordarUsu"> Recordarme</label>
            <button class="btn btn-lg btn-primary btn-block" type="submit">Login</button>
            <label class="textoCheckbox"> <a href="{{ url_for('logIn.register')}}">Registrarse</a></label>
        </form>
    </div>
</div>
{% endblock %}

app/templates/main.html
{% from 'bootstrap/form.html' import render_form, render_field %}
<!DOCTYPE html>
<html>
    <head>
        {% block head %}
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        {% block styles %}
            {{ bootstrap.load_css() }}
            <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
            <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        {% endblock %}
        {% block scripts %} {% endblock %}
        {% block title %}{% endblock %}
        {% endblock %}
    </head>
    <body>
        {% block navegacion %}
        <div class="containerNav">
            <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <a class="navbar-brand" href="#">Navbar</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
        
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item active">
                            <a class="nav-link" href="{{ url_for('Tienda.index') }}">Home <span class="sr-only">(current)</span></a>
                        </li>
                        {% if current_user.is_authenticated %}
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Estadisticas
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                <a class="nav-link" href="{{ url_for('Stats.usuarios') }}">Usuarios</a>
                                <a class="nav-link" href="{{ url_for('Stats.stats') }}">Pedidos</a>
                                <a class="nav-link" href="{{ url_for('Stats.almacenes') }}">Almacenes</a>
                            </div>
                        </li>
                        
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('anyadir.add_prod') }}">Añadir Producto</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('eliminar.rm_ped') }}">Eliminar Pedido</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('eliminar.rm_prod') }}">Eliminar Producto</a>
                        </li>
                        {% endif %}
                    </ul>
                    <ul class="navbar-nav ml-auto"></ul>
                    {% if current_user.is_authenticated %}
                        <a class="nav-link" href="{{ url_for('logIn.logout') }}">Salir</a>
                    {% else %}
                        <a class="nav-link" href="{{ url_for('logIn.login') }}">Iniciar sesion</a>
                    {% endif %}
                    </ul>
                </div>
            </nav>

        </div>
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
        {% endblock %}
        <div class="contenido">{% block contenido %}{% endblock %}</div>
    </body>

</html>

app/templates/registro.html
{% extends 'main.html' %}


{% block title %}<title>Log In</title>{% endblock %}
{% block contenido %}
<div class="bodyLogin">
    <div class="loginContainer">
        <form class="form-signin" method="post">
            <h2>Iniciar Sesión</h2>
            <input type="text" class="form-control" name="email" placeholder="Email" required="true" autofocus="" />                        
            <input type="password" class="form-control" name="password" placeholder="Password" required="true"/>
            <input type="text" class="form-control" name="nombre" placeholder="Nombre" required="true" autofocus="" />
            <input type="text" class="form-control" name="direccion" placeholder="Direccion" required="true" autofocus="" />
            <input type="text" class="form-control" name="telefono" placeholder="Telefono" required="true" autofocus="" />
            <a class="text" href="{{url_for('logIn.login')}}">Tienes cuenta?</a>
            <button class="btn btn-lg btn-primary btn-block" type="submit">Registro</button>
        </form>
    </div>
</div>
{% endblock %}

app/templates/stats.html
{% extends 'main.html' %}
{% block title %}<title>Pedidos</title>{% endblock %}
{% block scripts %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.5.0/Chart.min.js"></script>

{% endblock %}
{% block contenido %}
<div class="contenedorDatos">
    <table class="table">
        <thead class="thead-dark">
            <tr>
                <th class="columna" scope="col">Usuario</th>
                <th class="columna" scope="col">Producto</th>
                <th class="columna" scope="col">Estado</th>
                <th class="columna" scope="col">Cantidad</th>
            </tr>
        </thead>
        <tbody>
            {% for pedido in pedidos %}
                <tr>
                    {% for usuario in usuarios %}
                        {% if usuario.id==pedido.id_usuario %}
                            <td>{{usuario.nombre}}</td>         
                        {% endif %}
                    {% endfor %}
                    {% for producto in productos %}
                        {% if producto.id==pedido.id_productos %}
                            <td>{{producto.nombre}}</td>
                        {% endif %}
                    {% endfor %}
                    <td>{{pedido.estado}}</td>
                    <td>{{pedido.id}}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

    <nav>
        <div class="nav nav-tabs" id="nav-tab" role="tablist">
            <a class="nav-item nav-link active" id="nav-usuCiu-tab" data-toggle="tab" href="#nav-usuCiu" role="tab" aria-controls="nav-usuCiu" aria-selected="true">Estado envios</a>
            <a class="nav-item nav-link" id="nav-profile-tab" data-toggle="tab" href="#nav-profile" role="tab" aria-controls="nav-profile" aria-selected="false">Pedidos por usuario</a>
            <a class="nav-item nav-link" id="nav-contact-tab" data-toggle="tab" href="#nav-contact" role="tab" aria-controls="nav-contact" aria-selected="false">Pedidos por producto</a>
        </div>
    </nav>
    <div class="tab-content" id="nav-tabContent">
        <div class="tab-pane fade show active" id="nav-usuCiu" role="tabpanel" aria-labelledby="nav-usuCiu-tab">
            <canvas id="chartEstado" width="400" height="400"></canvas>
        </div>
        <div class="tab-pane fade" id="nav-profile" role="tabpanel" aria-labelledby="nav-profile-tab">
            <canvas id="chartPedidosPorUsuario" width="400" height="400"></canvas>
        </div>
        <div class="tab-pane fade" id="nav-contact" role="tabpanel" aria-labelledby="nav-contact-tab">
            <canvas id="chartPedidosPorProducto" width="400" height="400"></canvas>
        </div>
    </div>

</div>
<script>
    var ctx = document.getElementById("chartEstado");
    var dynamicColors = function() {
        var r = Math.floor(Math.random() * 255);
        var g = Math.floor(Math.random() * 255);
        var b = Math.floor(Math.random() * 255);
        return "rgb(" + r + "," + g + "," + b + ")";
    };

    var chartEstado = new Chart(ctx, {
        type: 'bar',
        data: {
            labels: [
                {% for item in cnt_estado %}
                    "{{ item[0] }}",
                {% endfor %}],
            datasets: [{
                label: 'Estado de los pedidos',
                backgroundColor: [
                    {% for item in cnt_estado %}
                        dynamicColors().toString(),
                    {% endfor %} 
                ],
                data: [
                    {% for item in cnt_estado %}
                        "{{ item[1] }}",
                    {% endfor %}],
            }]
        }
    });
</script>

<script>
    var cta = document.getElementById("chartPedidosPorUsuario");
    var ctb = document.getElementById("chartPedidosPorProducto");
    var dynamicColors = function() {
        var r = Math.floor(Math.random() * 255);
        var g = Math.floor(Math.random() * 255);
        var b = Math.floor(Math.random() * 255);
        return "rgb(" + r + "," + g + "," + b + ")";
    };

    var chartPedidosPorUsuario = new Chart(cta, {
        type: 'bar',
        data: {
            labels: [
            {% for item in cnt_usuarios %}
                {% for x in usuarios %}
                    {% if item[0]==x.id %}
                        "{{ x.nombre }}",
                    {% endif %}
                {% endfor %}
            {% endfor %}
            ],
            datasets: [{
                label: 'Pedidos por usuario',
                backgroundColor: [
                    {% for item in cnt_usuarios %}
                        dynamicColors().toString(),
                    {% endfor %} 
                ],
                data: [
                    {% for item in cnt_usuarios %}
                        "{{ item[1] }}",
                    {% endfor %}],
            }]
        }
    });

    var chartPedidosPorProducto = new Chart(ctb, {
        type: 'bar',
        data: {
            labels: [
            {% for item in cnt_productos %}
                {% for x in productos %}
                    {% if item[0]==x.id %}
                        "{{ x.nombre }}",
                    {% endif %}
                {% endfor %}
            {% endfor %}
            ],
            datasets: [{
                label: 'Pedidos por producto',
                backgroundColor: [
                    {% for item in cnt_productos %}
                        dynamicColors().toString(),
                    {% endfor %} 
                ],
                data: [{% for item in cnt_productos %}
                    "{{ item[1] }}",
                {% endfor %}],
            }]
        }
    });
</script>

{% endblock %}

app/templates/tienda.html
{% extends 'main.html' %}
{% block title %}<title>Tienda</title>{% endblock %}
{% block contenido %}
<div class="contenedorCards">
{% for producto in productos %}
        <div class="card">
            <h5 name="producto" class="card-title">{{ producto.nombre }}</h5>
            <p class="card-text">{{producto.categoria}}</p>
            <p class="card-text">{{producto.cantidad}}</p>
            <a name="prod"  class="btn btn-primary">COMPRAR</a>
        </div>
{% endfor %}
</div>

{% endblock %}